name: Rust

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ rust-build ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
