name: zig-build

on:
  push:
    branches: [zig-build]
  pull_request:
    branches: [zig-build]

jobs:
  build-on-ubuntu_windows:
    env:
      ZIG_VERSION: 0.15.2
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository @${{ matrix.os }}
        uses: actions/checkout@v3

      - name: Install Zig @${{ matrix.os }}
        uses: mlugg/setup-zig@v2
        with:
          version: $ZIG_VERSION

      - name: Build & Run @${{ matrix.os }}
        run: zig build run

      - name: Deploy to gh-pages
        if: matrix.os == 'ubuntu-latest'
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: build
