name: zig-build

on:
  push:
    branches: [ zig-build ]
  pull_request:
    branches: [ zig-build ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository ${{ matrix.os }}
        uses: actions/checkout@v3

      - name: Install Zig ${{ matrix.os }}
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      
      - name: Build&Run $${ matrix.os }}
        run: zig build run
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: build
